# Generated by Django 5.0.3 on 2024-03-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('mobile', 'password')},
        ),
    ]
