# Generated by Django 5.0.1 on 2024-03-13 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='order.order')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Заказ взят в работу')),
                ('is_started', models.BooleanField(default=False, verbose_name='Начата уборка')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Уборка закончена')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
            ],
            options={
                'verbose_name': 'статус заказа',
                'verbose_name_plural': 'статусы заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='cleaning_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.cleaningtype', verbose_name='Тип уборки'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='order',
            name='furniture_cluttered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.furniturecluttered', verbose_name='Заставленность мебелью'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='order',
            name='pollution_degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.pollutiondegree'),
        ),
        migrations.AddField(
            model_name='promo',
            name='cleaning_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.cleaningtype', verbose_name='Для какого типа уборки'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.promo', verbose_name='ПРОМОКОД'),
        ),
        migrations.AddField(
            model_name='order',
            name='things_cluttered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.thingscluttered', verbose_name='Заставленность вещами'),
        ),
    ]
