# Generated by Django 5.0.3 on 2024-03-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cleaningtype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningtype',
            name='subdescription',
            field=models.CharField(default=1, max_length=2000, verbose_name='Субописание уборки'),
            preserve_default=False,
        ),
    ]
