# Generated by Django 5.0.3 on 2024-03-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_cleaningtypecanaddlist_cleaning_type_can_add_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningtypecanadd',
            name='cleaning_type_locatiion',
        ),
        migrations.RemoveField(
            model_name='cleaningtypeinclude',
            name='cleaning_type_locatiion',
        ),
        migrations.AddField(
            model_name='cleaningtypelocation',
            name='can_add',
            field=models.ManyToManyField(to='order.cleaningtypecanadd', verbose_name='Можно добавить'),
        ),
        migrations.AddField(
            model_name='cleaningtypelocation',
            name='include',
            field=models.ManyToManyField(to='order.cleaningtypeinclude', verbose_name='Что входит'),
        ),
    ]
