# Generated by Django 5.0.3 on 2024-03-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_cleaningtypelocation_can_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningtypelocation',
            name='can_add',
            field=models.ManyToManyField(blank=True, to='order.cleaningtypecanadd', verbose_name='Можно добавить'),
        ),
        migrations.AlterField(
            model_name='cleaningtypelocation',
            name='include',
            field=models.ManyToManyField(blank=True, to='order.cleaningtypeinclude', verbose_name='Что входит'),
        ),
    ]
