# Generated by Django 5.0.3 on 2024-04-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_cleaningtype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningtypecanadd',
            name='can_add_list',
            field=models.ManyToManyField(blank=True, to='order.cleaningtypecanaddlist', verbose_name='Список что можно добавить'),
        ),
        migrations.AlterField(
            model_name='cleaningtypeinclude',
            name='include_list',
            field=models.ManyToManyField(blank=True, to='order.cleaningtypeincludelist', verbose_name='Список что входит'),
        ),
        migrations.AlterField(
            model_name='order',
            name='room_choices',
            field=models.CharField(choices=[('apartment', [('apart', 'Квартира')]), ('office', [('office', 'Офис')]), ('workshop', [('workshop', 'Производство/Мастерская')]), ('house', [('house', 'Загородный дом')]), ('yacht', [('yacht', 'Яхта')])], default='apartment', max_length=100, verbose_name='Тип помещения'),
        ),
    ]
