# Generated by Django 5.0.3 on 2024-04-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_room_choices_portfolioimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioimage',
            options={'permissions': [], 'verbose_name': 'Изображение портфолио', 'verbose_name_plural': 'Изображения портфолио'},
        ),
        migrations.AlterField(
            model_name='order',
            name='room_choices',
            field=models.CharField(choices=[('office', 'Офис'), ('workshop', 'Производство'), ('house', 'Загородный дом'), ('yacht', 'Яхта'), ('apartment', 'Квартира')], default='apartment', max_length=100, verbose_name='Тип помещения'),
        ),
    ]
