# Generated by Django 5.0.3 on 2024-04-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_room_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='room_choices',
            field=models.CharField(choices=[('yacht', 'Яхта'), ('house', 'Загородный дом'), ('apartment', 'Квартира'), ('office', 'Офис'), ('workshop', 'Производство')], default='apartment', max_length=100, verbose_name='Тип помещения'),
        ),
    ]
