# Generated by Django 5.0.3 on 2024-04-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_room_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimage',
            name='name',
            field=models.CharField(default='портфолио', max_length=100, verbose_name='название изображения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='room_choices',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('workshop', 'Производство'), ('house', 'Загородный дом'), ('office', 'Офис'), ('yacht', 'Яхта')], default='apartment', max_length=100, verbose_name='Тип помещения'),
        ),
    ]
