# Generated by Django 5.0.3 on 2024-04-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_portfolioimage_name_alter_order_room_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='room_choices',
            field=models.CharField(choices=[('workshop', 'Производство'), ('house', 'Загородный дом'), ('apartment', 'Квартира'), ('yacht', 'Яхта'), ('office', 'Офис')], default='apartment', max_length=100, verbose_name='Тип помещения'),
        ),
    ]
