# Generated by Django 5.0.3 on 2024-04-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_order_room_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='room_choices',
            field=models.CharField(choices=[('house', 'Загородный дом'), ('office', 'Офис'), ('yacht', 'Яхта'), ('apartment', 'Квартира'), ('workshop', 'Производство')], default='apartment', max_length=100, verbose_name='Тип помещения'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='picture',
            field=models.ImageField(upload_to='portfolio/%Y/%m/%d/', verbose_name='изображение'),
        ),
    ]
