# Generated by Django 5.0.3 on 2024-04-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_order_room_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='room_choices',
            field=models.CharField(choices=[('yacht', 'Яхта'), ('house', 'Загородный дом'), ('office', 'Офис'), ('workshop', 'Производство'), ('apartment', 'Квартира')], default='apartment', max_length=100, verbose_name='Тип помещения'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='name',
            field=models.CharField(default='Название', max_length=100, unique=True, verbose_name='название изображения'),
        ),
    ]
