# Generated by Django 5.0.3 on 2024-04-17 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_order_room_choices_alter_portfolioimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pollution_degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.pollutiondegree', verbose_name='Степень загрязнения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='room_choices',
            field=models.CharField(choices=[('workshop', 'Производство'), ('office', 'Офис'), ('yacht', 'Яхта'), ('apartment', 'Квартира'), ('house', 'Загородный дом')], default='apartment', max_length=100, verbose_name='Тип помещения'),
        ),
    ]
