# Generated by Django 5.0.3 on 2024-04-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_roomtype_remove_order_room_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='things_cluttered',
        ),
    ]
