# Generated by Django 5.0.3 on 2024-04-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_remove_order_things_cluttered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThingsCluttered',
        ),
    ]
