# Generated by Django 5.0.3 on 2024-04-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_roomtype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cleaning_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.cleaningtype', verbose_name='Тип уборки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='furniture_cluttered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.furniturecluttered', verbose_name='Заставленность мебелью'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pollution_degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.pollutiondegree', verbose_name='Степень загрязнения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.promo', verbose_name='ПРОМОКОД'),
        ),
    ]
