# Generated by Django 5.0.4 on 2024-04-27 11:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_alter_order_cleaning_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='price',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='price',
        ),
        migrations.AddField(
            model_name='feedback',
            name='cleaning_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='order.cleaningtype', verbose_name='Тип уборки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furniturecluttered',
            name='markup',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Наценка в процентах'),
        ),
        migrations.AddField(
            model_name='pollutiondegree',
            name='markup',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Наценка в процентах'),
        ),
        migrations.AddField(
            model_name='promo',
            name='markup',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка в процентах'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='markup',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Наценка в процентах'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Пожелания/комментарии'),
        ),
    ]
