# Generated by Django 5.0.4 on 2024-05-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_remove_promo_price_remove_roomtype_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='window_clean',
        ),
        migrations.AddField(
            model_name='order',
            name='is_deep_floor',
            field=models.BooleanField(default=False, verbose_name='Глубокая чистка пола'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_fridge',
            field=models.BooleanField(default=False, verbose_name='Мойка холодильника'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_garbage',
            field=models.BooleanField(default=False, verbose_name='Вынос мусора'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_linen',
            field=models.BooleanField(default=False, verbose_name='Погладить бельё'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_microwave',
            field=models.BooleanField(default=False, verbose_name='Мойка микроволновки'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_oven',
            field=models.BooleanField(default=False, verbose_name='Мойка духового шкафа'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_tile_joint',
            field=models.BooleanField(default=False, verbose_name='Чистка межплиточных швов'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_windows',
            field=models.BooleanField(default=False, verbose_name='Мойка окон'),
        ),
    ]
