# Generated by Django 5.0.4 on 2024-05-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_remove_order_window_clean_order_is_deep_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(max_length=10, verbose_name='Цена'),
        ),
    ]
