version: '3.6'

services:
  server:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/usr/src/server
    ports:
      - 8000:8000
    env_file:
      - ./server/.env
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cclean
      - POSTGRES_PASSWORD=bobercurwa
      - POSTGRES_DB=cclean

  client:
    build: ./client
    volumes:
      - ./client:/usr/src/client
    ports:
      - 80:80
    depends_on:
      - server
  
