# Generated by Django 5.0.3 on 2024-03-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='cleaning_type',
            field=models.CharField(verbose_name='Тип уборки'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, verbose_name='Номер телефона'),
        ),
    ]
