# Generated by Django 5.0.3 on 2024-03-20 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleaningtype',
            options={'permissions': [], 'verbose_name': 'Тип уборки', 'verbose_name_plural': 'Типы уборки'},
        ),
    ]
