# Generated by Django 5.0.3 on 2024-03-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_cleaningtype_subdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningtype',
            name='subdescription',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Субописание уборки'),
        ),
    ]
