# Generated by Django 5.0.3 on 2024-03-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_cleaningtype_subdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningtypeincludelist',
            name='cleaning_type_include',
        ),
        migrations.AddField(
            model_name='cleaningtypeincludelist',
            name='cleaning_type_include',
            field=models.ManyToManyField(related_name='include_list', to='order.cleaningtypeinclude', verbose_name='Категория(что входит в уборку)'),
        ),
    ]
