# Generated by Django 5.0.3 on 2024-03-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_cleaningtypeincludelist_cleaning_type_include_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningtypeincludelist',
            name='cleaning_type_include',
        ),
        migrations.AddField(
            model_name='cleaningtypeinclude',
            name='include_list',
            field=models.ManyToManyField(to='order.cleaningtypeincludelist', verbose_name='Список что входит'),
        ),
    ]
