# Generated by Django 5.0.3 on 2024-03-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_cleaningtypeincludelist_cleaning_type_include_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningtypecanaddlist',
            name='cleaning_type_can_add',
        ),
        migrations.AddField(
            model_name='cleaningtypecanadd',
            name='can_add_list',
            field=models.ManyToManyField(to='order.cleaningtypecanaddlist', verbose_name='Список что можно добавить'),
        ),
    ]
