# Generated by Django 5.0.3 on 2024-03-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_cleaningtypecanadd_cleaning_type_locatiion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningtypelocation',
            name='can_add',
            field=models.ManyToManyField(blank=True, null=True, to='order.cleaningtypecanadd', verbose_name='Можно добавить'),
        ),
        migrations.AlterField(
            model_name='cleaningtypelocation',
            name='include',
            field=models.ManyToManyField(blank=True, null=True, to='order.cleaningtypeinclude', verbose_name='Что входит'),
        ),
    ]
