# Generated by Django 5.0.1 on 2024-03-13 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='cleaning_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.cleaningtype', verbose_name='Тип уборки'),
        ),
    ]
