# Generated by Django 5.0.3 on 2024-03-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_lead_created_lead_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='comment',
            field=models.CharField(blank=True, null=True, verbose_name='комментарий'),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_treatmened',
            field=models.BooleanField(default=False, verbose_name='Обрабртано'),
        ),
    ]
