# Generated by Django 5.0.3 on 2024-04-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_lead_comment_lead_is_treatmened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='cleaning_type',
            field=models.CharField(max_length=100, verbose_name='Тип уборки'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='комментарий'),
        ),
    ]
