# Generated by Django 5.0.4 on 2024-04-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_alter_lead_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='price',
            field=models.CharField(blank=True, null=True, verbose_name='Предварительная цена'),
        ),
    ]
