# Generated by Django 5.0.4 on 2024-05-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_is_varified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_varified',
            new_name='is_verified',
        ),
    ]
